### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docker-ruby#13]
From the app logs:

```
{
  "level": 40,
  "branch": "renovate\/jekyll-3.x",
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm -v \"\/mnt\/renovate\/gh\/renovatebot\/website\":\"\/mnt\/renovate\/gh\/renovatebot\/website\" -w \"\/mnt\/renovate\/gh\/renovatebot\/website\" renovate\/ruby:2.3.8 bash -l -c \"ruby --version && gem install bundler -v 1.16.4 --no-document && bundle lock --update jekyll\"",
    "stdout": "ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]
",
    "stderr": "ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources
",
    "message": "Command failed: docker run --rm -v \"\/mnt\/renovate\/gh\/renovatebot\/website\":\"\/mnt\/renovate\/gh\/renovatebot\/website\" -w \"\/mnt\/renovate\/gh\/renovatebot\/website\" renovate\/ruby:2.3.8 bash -l -c \"ruby --version && gem install bundler -v 1.16.4 --no-document && bundle lock --update jekyll\"
ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources
",
    "stack": "Error: Command failed: docker run --rm -v \"\/mnt\/renovate\/gh\/renovatebot\/website\":\"\/mnt\/renovate\/gh\/renovatebot\/website\" -w \"\/mnt\/renovate\/gh\/renovatebot\/website\" renovate\/ruby:2.3.8 bash -l -c \"ruby --version && gem install bundler -v 1.16.4 --no-document && bundle lock --update jekyll\"
ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal\/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal\/child_process.js:259:5)"
  },
  "msg": "Failed to generate Gemfile.lock (unknown error)",
  "time": "2019-12-17T11:00:38.516Z"
}
```

**Comment by viceice** [comment]
@rarkins did you see this issue last months? I think this is fixed with our buildpack migration
